### PR TITLE
Test Added for Issue#32

### PR DESCRIPTION
**Pull request by jvfullam**

### CODE REVIEW

**Comment by jvfullam** [comment]
Travis build failed upon pull request. Double checking that build succeeds on local machine.

**Comment by jvfullam** [comment]
Merged updates to WASdev master into my feature branch (issue#32). Travis build passes now.

**Comment by jvfullam** [comment]
The test I wrote turns out to be implementation specific. It assumes that unresolved @Inject statements will have a default value. This is not the behavior of CDI injection.

We need a new test strategy for determining that parent-level properties are out of scope of child level artifacts.

**Comment by jvfullam** [comment]
Reopening this for now... it seems okay to try:

@Inject
@BatchProperty
String notPresentInBatchletPropertiesOfXML;

and assume that the String will resolve to a value of null.

**Comment by scottkurz** [comment]
Thanks for the helpful comments on the test strategy.

**Pull request merged**
